
module ApplicationHelper
    def get_skill(skillId)
        @skills = {
            0 => 'SKILL_NONE',
            1 => 'SKILL_HAND_TO_HAND',
            2 => 'SKILL_DAGGER',
            3 => 'SKILL_SWORD',
            4 => 'SKILL_GREAT_SWORD',
            5 => 'SKILL_AXE',
            6 => 'SKILL_GREAT_AXE',
            7 => 'SKILL_SCYTHE',
            8 => 'SKILL_POLEARM',
            9 => 'SKILL_KATANA',
            10 => 'SKILL_GREAT_KATANA',
            11 => 'SKILL_CLUB',
            12 => 'SKILL_STAFF',
            22 => 'SKILL_AUTOMATON_MELEE',
            23 => 'SKILL_AUTOMATON_RANGED',
            24 => 'SKILL_AUTOMATON_MAGIC',
            25 => 'SKILL_ARCHERY',
            26 => 'SKILL_MARKSMANSHIP',
            27 => 'SKILL_THROWING',
            28 => 'SKILL_GUARD',
            29 => 'SKILL_EVASION',
            30 => 'SKILL_SHIELD',
            31 => 'SKILL_PARRY',
            32 => 'SKILL_DIVINE_MAGIC',
            33 => 'SKILL_HEALING_MAGIC',
            34 => 'SKILL_ENHANCING_MAGIC',
            35 => 'SKILL_ENFEEBLING_MAGIC',
            36 => 'SKILL_ELEMENTAL_MAGIC',
            37 => 'SKILL_DARK_MAGIC',
            38 => 'SKILL_SUMMONING_MAGIC',
            39 => 'SKILL_NINJUTSU',
            40 => 'SKILL_SINGING',
            41 => 'SKILL_STRING_INSTRUMENT',
            42 => 'SKILL_WIND_INSTRUMENT',
            43 => 'SKILL_BLUE_MAGIC',
            44 => 'SKILL_GEOMANCY',
            45 => 'SKILL_HANDBELL',
            48 => 'SKILL_FISHING',
            49 => 'SKILL_WOODWORKING',
            50 => 'SKILL_SMITHING',
            51 => 'SKILL_GOLDSMITHING',
            52 => 'SKILL_CLOTHCRAFT',
            53 => 'SKILL_LEATHERCRAFT',
            54 => 'SKILL_BONECRAFT',
            55 => 'SKILL_ALCHEMY',
            56 => 'SKILL_COOKING',
            57 => 'SKILL_SYNERGY',
            58 => 'SKILL_RID',
            59 => 'SKILL_DIG'
        }
        @skills[skillId]
    end

    def get_dmg_type(dmgTypeId)
        @dmgTypes = {
            0 => 'NONE',
            1 => 'PIERCING',
            2 => 'SLASHING',
            3 => 'IMPACT',
            4 => 'HTH',
            5 => 'ELEMENTAL',
            6 => 'FIRE',
            7 => 'ICE',
            8 => 'WIND',
            9 => 'EARTH',
            10 => 'LIGHTNING',
            11 => 'WATER',
            12 => 'LIGHT',
            13 => 'DARK'
        }
        @dmgTypes[dmgTypeId]
    end

    def get_valid_targets(targetId)
        @validTargets = {
            1 => 'TARGET_SELF',
            2 => 'TARGET_PLAYER_PARTY',
            4 => 'TARGET_ENEMY',
            8 => 'TARGET_PLAYER_ALLIANCE',
            16 => 'TARGET_PLAYER',
            32 => 'TARGET_PLAYER_DEAD',
            64 => 'TARGET_NPC',
            128 => 'TARGET_PLAYER_PARTY_PIANISSIMO',
            256 => 'TARGET_PET'
        }
        @validTargets[targetId]
    end

    def get_mod(modId)
        @mods = {
            0 =>'NONE',
            1 =>'DEF',
            2 =>'HP',
            3 =>'HPP',
            4 =>'CONVMPTOHP',
            5 =>'MP',
            6 =>'MPP',
            7 =>'CONVHPTOMP',
            8 =>'STR',
            9 =>'DEX',
            10 =>'VIT',
            11 =>'AGI',
            12 =>'INT',
            13 =>'MND',
            14 =>'CHR',
            15 =>'FIREDEF',
            16 =>'ICEDEF',
            17 =>'WINDDEF',
            18 =>'EARTHDEF',
            19 =>'THUNDERDEF',
            20 =>'WATERDEF',
            21 =>'LIGHTDEF',
            22 =>'DARKDEF',
            23 =>'ATT',
            24 =>'RATT',
            25 =>'ACC',
            26 =>'RACC',
            27 =>'ENMITY',
            427 =>'ENMITY_LOSS_REDUCTION',
            28 =>'MATT',
            29 =>'MDEF',
            30 =>'MACC',
            31 =>'MEVA',
            32 =>'FIREATT',
            33 =>'ICEATT',
            34 =>'WINDATT',
            35 =>'EARTHATT',
            36 =>'THUNDERATT',
            37 =>'WATERATT',
            38 =>'LIGHTATT',
            39 =>'DARKATT',
            40 =>'FIREACC',
            41 =>'ICEACC',
            42 =>'WINDACC',
            43 =>'EARTHACC',
            44 =>'THUNDERACC',
            45 =>'WATERACC',
            46 =>'LIGHTACC',
            47 =>'DARKACC',
            48 =>'WSACC',
            49 =>'SLASHRES',
            50 =>'PIERCERES',
            51 =>'IMPACTRES',
            52 =>'HTHRES',
            54 =>'FIRERES',
            55 =>'ICERES',
            56 =>'WINDRES',
            57 =>'EARTHRES',
            58 =>'THUNDERRES',
            59 =>'WATERRES',
            60 =>'LIGHTRES',
            61 =>'DARKRES',
            62 =>'ATTP',
            63 =>'DEFP',
            64 =>'COMBAT_SKILLUP_RATE', # % increase in skillup combat rate
            65 =>'MAGIC_SKILLUP_RATE', # % increase in skillup magic rate
            66 =>'RATTP',
            68 =>'EVA',
            69 =>'RDEF',
            70 =>'REVA',
            71 =>'MPHEAL',
            72 =>'HPHEAL',
            73 =>'STORETP',
            80 =>'HTH',
            81 =>'DAGGER',
            82 =>'SWORD',
            83 =>'GSWORD',
            84 =>'AXE',
            85 =>'GAXE',
            86 =>'SCYTHE',
            87 =>'POLEARM',
            88 =>'KATANA',
            89 =>'GKATANA',
            90 =>'CLUB',
            91 =>'STAFF',
            92 =>'RAMPART_DURATION',  # Rampart duration in seconds
            93 =>'FLEE_DURATION',  # Flee duration in seconds
            94 =>'MEDITATE_DURATION',  # Meditate duration in seconds
            95 =>'WARDING_CIRCLE_DURATION',  # Warding Circle duration in seconds
            96 =>'SOULEATER_EFFECT',  # Souleater power in percents
            906 =>'DESPERATE_BLOWS', # Adds ability haste to Last Resort
            907 =>'STALWART_SOUL', # Reduces damage taken from Souleater
            97 =>'BOOST_EFFECT',  # Boost power in tenths
            98 =>'CAMOUFLAGE_DURATION',  # Camouflage duration in percents
            101 =>'AUTO_MELEE_SKILL',
            102 =>'AUTO_RANGED_SKILL',
            103 =>'AUTO_MAGIC_SKILL',
            104 =>'ARCHERY',
            105 =>'MARKSMAN',
            106 =>'THROW',
            107 =>'GUARD',
            108 =>'EVASION',
            109 =>'SHIELD',
            110 =>'PARRY',
            111 =>'DIVINE',
            112 =>'HEALING',
            113 =>'ENHANCE',
            114 =>'ENFEEBLE',
            115 =>'ELEM',
            116 =>'DARK',
            117 =>'SUMMONING',
            118 =>'NINJUTSU',
            119 =>'SINGING',
            120 =>'STRING',
            121 =>'WIND',
            122 =>'BLUE',
            123 =>'CHAKRA_MULT', # Chakra multiplier increase
            124 =>'CHAKRA_REMOVAL', # Extra statuses removed by Chakra
            125 =>'SUPPRESS_OVERLOAD', # Kenkonken "Suppresses Overload" mod. Unclear how this works exactly. Requires testing on retail.
            126 =>'BP_DAMAGE', # Blood Pact: Rage Damage increase percentage
            127 =>'FISH',
            128 =>'WOOD',
            129 =>'SMITH',
            130 =>'GOLDSMITH',
            131 =>'CLOTH',
            132 =>'LEATHER',
            133 =>'BONE',
            134 =>'ALCHEMY',
            135 =>'COOK',
            136 =>'SYNERGY',
            137 =>'RIDING',
            144 =>'ANTIHQ_WOOD',
            145 =>'ANTIHQ_SMITH',
            146 =>'ANTIHQ_GOLDSMITH',
            147 =>'ANTIHQ_CLOTH',
            148 =>'ANTIHQ_LEATHER',
            149 =>'ANTIHQ_BONE',
            150 =>'ANTIHQ_ALCHEMY',
            151 =>'ANTIHQ_COOK',
            160 =>'DMG',
            161 =>'DMGPHYS',
            190 =>'DMGPHYS_II', # Physical Damage Taken II % (Burtgang)
            162 =>'DMGBREATH',
            163 =>'DMGMAGIC',
            831 =>'DMGMAGIC_II', # Magic Damage Taken II % (Aegis)
            164 =>'DMGRANGE',
            387 =>'UDMGPHYS',
            388 =>'UDMGBREATH',
            389 =>'UDMGMAGIC',
            390 =>'UDMGRANGE',
            165 =>'CRITHITRATE',
            421 =>'CRIT_DMG_INCREASE',
            964 =>'RANGED_CRIT_DMG_INCREASE', # Increases ranged critical damage by a percent
            166 =>'ENEMYCRITRATE',
            908 =>'CRIT_DEF_BONUS', # Reduces crit hit damage
            562 =>'MAGIC_CRITHITRATE',
            563 =>'MAGIC_CRIT_DMG_INCREASE',
            167 =>'HASTE_MAGIC',
            168 =>'SPELLINTERRUPT',
            169 =>'MOVE', # % Movement Speed
            972 =>'MOUNT_MOVE', # % Mount Movement Speed
            170 =>'FASTCAST',
            407 =>'UFASTCAST',
            519 =>'CURE_CAST_TIME',
            901 =>'ELEMENTAL_CELERITY', # Quickens Elemental Magic Casting
            171 =>'DELAY',
            172 =>'RANGED_DELAY',
            173 =>'MARTIAL_ARTS',
            174 =>'SKILLCHAINBONUS',
            175 =>'SKILLCHAINDMG',
            978 =>'MAX_SWINGS',
            979 =>'ADDITIONAL_SWING_CHANCE',
            176 =>'FOOD_HPP',
            177 =>'FOOD_HP_CAP',
            178 =>'FOOD_MPP',
            179 =>'FOOD_MP_CAP',
            180 =>'FOOD_ATTP',
            181 =>'FOOD_ATT_CAP',
            182 =>'FOOD_DEFP',
            183 =>'FOOD_DEF_CAP',
            184 =>'FOOD_ACCP',
            185 =>'FOOD_ACC_CAP',
            186 =>'FOOD_RATTP',
            187 =>'FOOD_RATT_CAP',
            188 =>'FOOD_RACCP',
            189 =>'FOOD_RACC_CAP',
            99 =>'FOOD_MACCP',
            100 =>'FOOD_MACC_CAP',
            937 =>'FOOD_DURATION', # Percentage to increase food duration
            224 =>'VERMIN_KILLER',
            225 =>'BIRD_KILLER',
            226 =>'AMORPH_KILLER',
            227 =>'LIZARD_KILLER',
            228 =>'AQUAN_KILLER',
            229 =>'PLANTOID_KILLER',
            230 =>'BEAST_KILLER',
            231 =>'UNDEAD_KILLER',
            232 =>'ARCANA_KILLER',
            233 =>'DRAGON_KILLER',
            234 =>'DEMON_KILLER',
            235 =>'EMPTY_KILLER',
            236 =>'HUMANOID_KILLER',
            237 =>'LUMORIAN_KILLER',
            238 =>'LUMINION_KILLER',
            240 =>'SLEEPRES',
            241 =>'POISONRES',
            242 =>'PARALYZERES',
            243 =>'BLINDRES',
            244 =>'SILENCERES',
            245 =>'VIRUSRES',
            246 =>'PETRIFYRES',
            247 =>'BINDRES',
            248 =>'CURSERES',
            249 =>'GRAVITYRES',
            250 =>'SLOWRES',
            251 =>'STUNRES',
            252 =>'CHARMRES',
            253 =>'AMNESIARES',
            254 =>'LULLABYRES',
            255 =>'DEATHRES',
            958 =>'STATUSRES', # "Resistance to All Status Ailments"
            256 =>'AFTERMATH',
            257 =>'PARALYZE',
            258 =>'MIJIN_RERAISE',
            259 =>'DUAL_WIELD',
            288 =>'DOUBLE_ATTACK',
            289 =>'SUBTLE_BLOW',
            973 =>'SUBTLE_BLOW_II', # Subtle Blow II Effect (Cap 50%) Total Effect (SB + SB_II cap 75%)
            290 =>'ENF_MAG_POTENCY', # Increases Enfeebling magic potency %
            291 =>'COUNTER',
            292 =>'KICK_ATTACK_RATE',
            293 =>'AFFLATUS_SOLACE',
            294 =>'AFFLATUS_MISERY',
            295 =>'CLEAR_MIND',
            296 =>'CONSERVE_MP',
            297 =>'ENHANCES_SABOTEUR', # Increases Saboteur Potency %
            298 =>'STEAL',
            896 =>'DESPOIL',
            883 =>'PERFECT_DODGE', # Increases Perfect Dodge duration in seconds
            299 =>'BLINK',
            300 =>'STONESKIN',
            301 =>'PHALANX',
            302 =>'TRIPLE_ATTACK',
            303 =>'TREASURE_HUNTER',
            304 =>'TAME',
            305 =>'RECYCLE',
            306 =>'ZANSHIN',
            307 =>'UTSUSEMI',
            900 =>'UTSUSEMI_BONUS', # Extra shadows from gear
            308 =>'NINJA_TOOL',
            309 =>'BLUE_POINTS', # Tracks extra blue points
            945 =>'BLUE_LEARN_CHANCE', # Additional chance to learn blue magic
            316 =>'DMG_REFLECT',
            317 =>'ROLL_ROGUES',
            318 =>'ROLL_GALLANTS',
            319 =>'ROLL_CHAOS',
            320 =>'ROLL_BEAST',
            321 =>'ROLL_CHORAL',
            322 =>'ROLL_HUNTERS',
            323 =>'ROLL_SAMURAI',
            324 =>'ROLL_NINJA',
            325 =>'ROLL_DRACHEN',
            326 =>'ROLL_EVOKERS',
            327 =>'ROLL_MAGUS',
            328 =>'ROLL_CORSAIRS',
            329 =>'ROLL_PUPPET',
            330 =>'ROLL_DANCERS',
            331 =>'ROLL_SCHOLARS',
        # Corsair Rolls Level 65+
            869 =>'ROLL_BOLTERS',
            870 =>'ROLL_CASTERS',
            871 =>'ROLL_COURSERS',
            872 =>'ROLL_BLITZERS',
            873 =>'ROLL_TACTICIANS',
            874 =>'ROLL_ALLIES',
            875 =>'ROLL_MISERS',
            876 =>'ROLL_COMPANIONS',
            877 =>'ROLL_AVENGERS',
            878 =>'ROLL_NATURALISTS',
            879 =>'ROLL_RUNEISTS',
            332 =>'BUST',
            333 =>'FINISHING_MOVES',
            490 =>'SAMBA_DURATION', # Samba duration bonus
            491 =>'WALTZ_POTENTCY', # Waltz Potentcy Bonus
            492 =>'JIG_DURATION', # Jig duration bonus in percents
            493 =>'VFLOURISH_MACC', # Violent Flourish accuracy bonus
            494 =>'STEP_FINISH', # Bonus finishing moves from steps
            403 =>'STEP_ACCURACY', # Accuracy bonus for steps
            497 =>'WALTZ_DELAY', # Waltz Ability Delay modifier (-1 mod is -1 second)
            498 =>'SAMBA_PDURATION', # Samba percent duration bonus
            340 =>'WIDESCAN',
            420 =>'BARRAGE_ACC',
            341 =>'ENSPELL',
            342 =>'SPIKES',
            343 =>'ENSPELL_DMG',
            856 =>'ENSPELL_CHANCE',
            344 =>'SPIKES_DMG',
            345 =>'TP_BONUS',
            346 =>'PERPETUATION_REDUCTION',
            347 =>'FIRE_AFFINITY_DMG',
            348 =>'ICE_AFFINITY_DMG',
            349 =>'WIND_AFFINITY_DMG',
            350 =>'EARTH_AFFINITY_DMG',
            351 =>'THUNDER_AFFINITY_DMG',
            352 =>'WATER_AFFINITY_DMG',
            353 =>'LIGHT_AFFINITY_DMG',
            354 =>'DARK_AFFINITY_DMG',

            544 =>'FIRE_AFFINITY_ACC',
            545 =>'ICE_AFFINITY_ACC',
            546 =>'WIND_AFFINITY_ACC',
            547 =>'EARTH_AFFINITY_ACC',
            548 =>'THUNDER_AFFINITY_ACC',
            549 =>'WATER_AFFINITY_ACC',
            550 =>'LIGHT_AFFINITY_ACC',
            551 =>'DARK_AFFINITY_ACC',

            553 =>'FIRE_AFFINITY_PERP',
            554 =>'ICE_AFFINITY_PERP',
            555 =>'WIND_AFFINITY_PERP',
            556 =>'EARTH_AFFINITY_PERP',
            557 =>'THUNDER_AFFINITY_PERP',
            558 =>'WATER_AFFINITY_PERP',
            559 =>'LIGHT_AFFINITY_PERP',
            560 =>'DARK_AFFINITY_PERP',

            355 =>'ADDS_WEAPONSKILL',
            356 =>'ADDS_WEAPONSKILL_DYN',
            357 =>'BP_DELAY',
            358 =>'STEALTH',
            359 =>'RAPID_SHOT',
            360 =>'CHARM_TIME',
            361 =>'JUMP_TP_BONUS',
            362 =>'JUMP_ATT_BONUS',
            363 =>'HIGH_JUMP_ENMITY_REDUCTION',
            364 =>'REWARD_HP_BONUS',
            365 =>'SNAP_SHOT',
            366 =>'MAIN_DMG_RATING',
            367 =>'SUB_DMG_RATING',
            368 =>'REGAIN',
            369 =>'REFRESH',
            370 =>'REGEN',
            371 =>'AVATAR_PERPETUATION',
            372 =>'WEATHER_REDUCTION',
            373 =>'DAY_REDUCTION',
            374 =>'CURE_POTENCY',
            260 =>'CURE_POTENCY_II', # % cure potency II | bonus from gear is capped at 30
            375 =>'CURE_POTENCY_RCVD',
            376 =>'RANGED_DMG_RATING',
            380 =>'DELAYP',
            381 =>'RANGED_DELAYP',
            382 =>'EXP_BONUS',
            383 =>'HASTE_ABILITY',
            384 =>'HASTE_GEAR',
            385 =>'SHIELD_BASH',
            386 =>'KICK_DMG',
            391 =>'CHARM_CHANCE',
            392 =>'WEAPON_BASH',
            393 =>'BLACK_MAGIC_COST',
            394 =>'WHITE_MAGIC_COST',
            395 =>'BLACK_MAGIC_CAST',
            396 =>'WHITE_MAGIC_CAST',
            397 =>'BLACK_MAGIC_RECAST',
            398 =>'WHITE_MAGIC_RECAST',
            399 =>'ALACRITY_CELERITY_EFFECT',
            334 =>'LIGHT_ARTS_EFFECT',
            335 =>'DARK_ARTS_EFFECT',
            336 =>'LIGHT_ARTS_SKILL',
            337 =>'DARK_ARTS_SKILL',
            338 =>'LIGHT_ARTS_REGEN', # Regen bonus HP from Light Arts and Tabula Rasa
            339 =>'REGEN_DURATION',
            478 =>'HELIX_EFFECT',
            477 =>'HELIX_DURATION',
            400 =>'STORMSURGE_EFFECT',
            401 =>'SUBLIMATION_BONUS',
            489 =>'GRIMOIRE_SPELLCASTING', # "Grimoire: Reduces spellcasting time" bonus
            402 =>'WYVERN_BREATH',
            404 =>'REGEN_DOWN', # poison
            405 =>'REFRESH_DOWN', # plague, reduce mp
            406 =>'REGAIN_DOWN', # plague, reduce tp
            311 =>'MAGIC_DAMAGE', #  Magic damage added directly to the spell's base damage

        # Gear set modifiers
            408 =>'DA_DOUBLE_DAMAGE', # Double attack's double damage chance %.
            409 =>'TA_TRIPLE_DAMAGE', # Triple attack's triple damage chance %.
            410 =>'ZANSHIN_DOUBLE_DAMAGE', # Zanshin's double damage chance %.
            479 =>'RAPID_SHOT_DOUBLE_DAMAGE', # Rapid shot's double damage chance %.
            480 =>'ABSORB_DMG_CHANCE', # Chance to absorb damage %
            481 =>'EXTRA_DUAL_WIELD_ATTACK', # Chance to land an extra attack when dual wielding
            482 =>'EXTRA_KICK_ATTACK', # Occasionally allows a second Kick Attack during an attack round without the use of Footwork.
            415 =>'SAMBA_DOUBLE_DAMAGE', # Double damage chance when samba is up.
            416 =>'NULL_PHYSICAL_DAMAGE', # Occasionally annuls damage from physical attacks, in percents
            417 =>'QUICK_DRAW_TRIPLE_DAMAGE', # Chance to do triple damage with quick draw.
            418 =>'BAR_ELEMENT_NULL_CHANCE', # Bar Elemental spells will occasionally nullify damage of the same element.
            419 =>'GRIMOIRE_INSTANT_CAST', # Spells that match your current Arts will occasionally cast instantly, without recast.
            543 =>'COUNTERSTANCE_EFFECT', # Counterstance effect in percents
            552 =>'DODGE_EFFECT', # Dodge effect in percents
            561 =>'FOCUS_EFFECT', # Focus effect in percents
            835 =>'MUG_EFFECT', # Mug effect as multiplier
            884 =>'ACC_COLLAB_EFFECT', # Increases amount of enmity transferred
            885 =>'HIDE_DURATION', # Hide duration increase (percentage based
            897 =>'GILFINDER', # Gil % increase
            836 =>'REVERSE_FLOURISH_EFFECT', # Reverse Flourish effect in tenths of squared term multiplier
            837 =>'SENTINEL_EFFECT', # Sentinel effect in percents
            838 =>'REGEN_MULTIPLIER', # Regen base multiplier

            422 =>'DOUBLE_SHOT_RATE', # The rate that double shot can proc
            423 =>'VELOCITY_SNAPSHOT_BONUS', # Increases Snapshot whilst Velocity Shot is up.
            424 =>'VELOCITY_RATT_BONUS', # Increases Ranged Attack whilst Velocity Shot is up.
            425 =>'SHADOW_BIND_EXT', # Extends the time of shadowbind
            426 =>'ABSORB_PHYSDMG_TO_MP', # Absorbs a percentage of physical damage taken to MP.
            485 =>'SHIELD_MASTERY_TP', # Shield mastery TP bonus when blocking with a shield
            428 =>'PERFECT_COUNTER_ATT', # Raises weapon damage by 20 when countering while under the Perfect Counter effects. This also affects Weapon Rank (though not if fighting barehanded).
            429 =>'FOOTWORK_ATT_BONUS', # Raises the attack bonus of Footwork. (Tantra Gaiters +2 raise 100/1024 to 152/1024)

            433 =>'MINNE_EFFECT', #
            434 =>'MINUET_EFFECT', #
            435 =>'PAEON_EFFECT', #
            436 =>'REQUIEM_EFFECT', #
            437 =>'THRENODY_EFFECT', #
            438 =>'MADRIGAL_EFFECT', #
            439 =>'MAMBO_EFFECT', #
            440 =>'LULLABY_EFFECT', #
            441 =>'ETUDE_EFFECT', #
            442 =>'BALLAD_EFFECT', #
            443 =>'MARCH_EFFECT', #
            444 =>'FINALE_EFFECT', #
            445 =>'CAROL_EFFECT', #
            446 =>'MAZURKA_EFFECT', #
            447 =>'ELEGY_EFFECT', #
            448 =>'PRELUDE_EFFECT', #
            449 =>'HYMNUS_EFFECT', #
            450 =>'VIRELAI_EFFECT', #
            451 =>'SCHERZO_EFFECT', #
            452 =>'ALL_SONGS_EFFECT', #
            453 =>'MAXIMUM_SONGS_BONUS', #
            454 =>'SONG_DURATION_BONUS', #
            455 =>'SONG_SPELLCASTING_TIME', #

            411 =>'QUICK_DRAW_DMG', #
            191 =>'QUICK_DRAW_MACC', # Quick draw magic accuracy
            430 =>'QUAD_ATTACK', # Quadruple attack chance.

            432 =>'ENSPELL_DMG_BONUS',

            459 =>'FIRE_ABSORB', # Occasionally absorbs fire elemental damage, in percents
            460 =>'ICE_ABSORB', # Occasionally absorbs ice elemental damage, in percents
            461 =>'WIND_ABSORB', # Occasionally absorbs wind elemental damage, in percents
            462 =>'EARTH_ABSORB', # Occasionally absorbs earth elemental damage, in percents
            463 =>'LTNG_ABSORB', # Occasionally absorbs thunder elemental damage, in percents
            464 =>'WATER_ABSORB', # Occasionally absorbs water elemental damage, in percents
            465 =>'LIGHT_ABSORB', # Occasionally absorbs light elemental damage, in percents
            466 =>'DARK_ABSORB', # Occasionally absorbs dark elemental damage, in percents

            467 =>'FIRE_NULL', #
            468 =>'ICE_NULL', #
            469 =>'WIND_NULL', #
            470 =>'EARTH_NULL', #
            471 =>'LTNG_NULL', #
            472 =>'WATER_NULL', #
            473 =>'LIGHT_NULL', #
            474 =>'DARK_NULL', #

            475 =>'MAGIC_ABSORB', # Occasionally absorbs magic damage taken, in percents
            476 =>'MAGIC_NULL', # Occasionally annuls magic damage taken, in percents
            512 =>'PHYS_ABSORB', # Occasionally absorbs physical damage taken, in percents
            516 =>'ABSORB_DMG_TO_MP', # Unlike PLD gear mod, works on all damage types (Ethereal Earring)

            483 =>'WARCRY_DURATION', # Warcy duration bonus from gear
            484 =>'AUSPICE_EFFECT', # Auspice Subtle Blow Bonus
            486 =>'TACTICAL_PARRY', # Tactical Parry TP Bonus
            487 =>'MAG_BURST_BONUS', # Magic Burst Bonus
            488 =>'INHIBIT_TP', # Inhibits TP Gain (percent)

            496 =>'GOV_CLEARS', # Tracks GoV page completion (for 4% bonus on rewards).

        # Reraise (Auto Reraise, will be used by ATMA)
            456 =>'RERAISE_I', # Reraise.
            457 =>'RERAISE_II', # Reraise II.
            458 =>'RERAISE_III', # Reraise III.

            431 =>'ADDITIONAL_EFFECT', # All additional effects
            499 =>'ITEM_SPIKES_TYPE', # Type spikes an item has
            500 =>'ITEM_SPIKES_DMG', # Damage of an items spikes
            501 =>'ITEM_SPIKES_CHANCE', # Chance of an items spike proc
            503 =>'FERAL_HOWL_DURATION', # +20% duration per merit when wearing augmented Monster Jackcoat +2
            504 =>'MANEUVER_BONUS', # Maneuver Stat Bonus
            505 =>'OVERLOAD_THRESH', # Overload Threshold Bonus
            847 =>'BURDEN_DECAY', # Increases amount of burden removed per tick
            853 =>'REPAIR_EFFECT', # Removes # of status effects from the Automaton
            854 =>'REPAIR_POTENCY', # Note: Only affects amount regenerated by a %, not the instant restore!
            855 =>'PREVENT_OVERLOAD', # Overloading erases a water maneuver (except on water overloads) instead, if there is one
            506 =>'EXTRA_DMG_CHANCE', # Proc rate of OCC_DO_EXTRA_DMG. 111 would be 11.1%
            507 =>'OCC_DO_EXTRA_DMG', # Multiplier for "Occasionally do x times normal damage". 250 would be 2.5 times damage.

            863 =>'REM_OCC_DO_DOUBLE_DMG', # Proc rate for REM Aftermaths that apply "Occasionally do double damage"
            864 =>'REM_OCC_DO_TRIPLE_DMG', # Proc rate for REM Aftermaths that apply "Occasionally do triple damage"

            867 =>'REM_OCC_DO_DOUBLE_DMG_RANGED', # Ranged attack specific
            868 =>'REM_OCC_DO_TRIPLE_DMG_RANGED', # Ranged attack specific

            865 =>'MYTHIC_OCC_ATT_TWICE', # Proc rate for "Occasionally attacks twice"
            866 =>'MYTHIC_OCC_ATT_THRICE', # Proc rate for "Occasionally attacks thrice"

            412 =>'EAT_RAW_FISH', #
            413 =>'EAT_RAW_MEAT', #

            67 =>'ENHANCES_CURSNA_RCVD',  # Potency of "Cursna" effects received
            310 =>'ENHANCES_CURSNA', # Raises success rate of Cursna when removing effect (like Doom) that are not 100% chance to remove
            495 =>'ENHANCES_HOLYWATER', # Used by gear with the "Enhances Holy Water" or "Holy Water+" attribute

            414 =>'RETALIATION', # Increases damage of Retaliation hits
            508 =>'THIRD_EYE_COUNTER_RATE', # Adds counter to 3rd eye anticipates & if using Seigan counter rate is increased by 15%
            839 =>'THIRD_EYE_ANTICIPATE_RATE', # Adds anticipate rate in percents

            509 =>'CLAMMING_IMPROVED_RESULTS', #
            510 =>'CLAMMING_REDUCED_INCIDENTS', #
            511 =>'CHOCOBO_RIDING_TIME', # Increases chocobo riding time
            513 =>'HARVESTING_RESULT', # Improves harvesting results
            514 =>'LOGGING_RESULT', # Improves logging results
            515 =>'MINING_RESULT', # Improves mining results
            517 =>'EGGHELM', # Egg Helm (Chocobo Digging)

            518 =>'SHIELDBLOCKRATE', # Affects shield block rate, percent based
            312 =>'SCAVENGE_EFFECT', #
            313 =>'DIA_DOT', # Increases the DoT damage of Dia
            314 =>'SHARPSHOT', # Sharpshot accuracy bonus
            315 =>'ENH_DRAIN_ASPIR', # % damage boost to Drain and Aspir
            874 =>'SNEAK_ATK_DEX', # % DEX boost to Sneak Attack (if gear mod, needs to be equipped on hit)
            520 =>'TRICK_ATK_AGI', # % AGI boost to Trick Attack (if gear mod, needs to be equipped on hit)
            522 =>'NIN_NUKE_BONUS', # magic attack bonus for NIN nukes
            911 =>'DAKEN', # Chance to throw shuriken on attack
            523 =>'AMMO_SWING', # Extra swing rate w/ ammo (ie. Jailer weapons). Use gearsets, and does nothing for non-players.
            826 =>'AMMO_SWING_TYPE', # For the handedness of the weapon - 1h (1) vs. 2h/h2h (2). h2h can safely use the same function as 2h.
            528 =>'ROLL_RANGE', # Additional range for COR roll abilities.
            881 =>'PHANTOM_ROLL', # Phantom Roll+ Effect from SOA Rings.
            882 =>'PHANTOM_DURATION', # Phantom Roll Duration +.

            529 =>'ENHANCES_REFRESH', # "Enhances Refresh" adds +1 per modifier to spell's tick result.
            530 =>'NO_SPELL_MP_DEPLETION', # % to not deplete MP on spellcast.
            531 =>'FORCE_FIRE_DWBONUS', # Set to 1 to force fire day/weather spell bonus/penalty. Do not have it total more than 1.
            532 =>'FORCE_ICE_DWBONUS', # Set to 1 to force ice day/weather spell bonus/penalty. Do not have it total more than 1.
            533 =>'FORCE_WIND_DWBONUS', # Set to 1 to force wind day/weather spell bonus/penalty. Do not have it total more than 1.
            534 =>'FORCE_EARTH_DWBONUS', # Set to 1 to force earth day/weather spell bonus/penalty. Do not have it total more than 1.
            535 =>'FORCE_LIGHTNING_DWBONUS', # Set to 1 to force lightning day/weather spell bonus/penalty. Do not have it total more than 1.
            536 =>'FORCE_WATER_DWBONUS', # Set to 1 to force water day/weather spell bonus/penalty. Do not have it total more than 1.
            537 =>'FORCE_LIGHT_DWBONUS', # Set to 1 to force light day/weather spell bonus/penalty. Do not have it total more than 1.
            538 =>'FORCE_DARK_DWBONUS', # Set to 1 to force dark day/weather spell bonus/penalty. Do not have it total more than 1.
            539 =>'STONESKIN_BONUS_HP', # Bonus "HP" granted to Stoneskin spell.
            540 =>'ENHANCES_ELEMENTAL_SIPHON', # Bonus Base MP added to Elemental Siphon skill.
            541 =>'BP_DELAY_II', # Blood Pact Delay Reduction II
            542 =>'JOB_BONUS_CHANCE', # Chance to apply job bonus to COR roll without having the job in the party.
            565 =>'DAY_NUKE_BONUS', # Bonus damage from "Elemental magic affected by day" (Sorc. Tonban)
            566 =>'IRIDESCENCE', # Iridescence trait (additional weather damage/penalty)
            567 =>'BARSPELL_AMOUNT', # Additional elemental resistance granted by bar- spells
            827 =>'BARSPELL_MDEF_BONUS', # Extra magic defense bonus granted to the bar- spell effect
            568 =>'RAPTURE_AMOUNT', # Bonus amount added to Rapture effect
            569 =>'EBULLIENCE_AMOUNT', # Bonus amount added to Ebullience effect
            829 =>'WYVERN_EFFECTIVE_BREATH', # Increases the threshold for triggering healing breath
            832 =>'AQUAVEIL_COUNT', # Modifies the amount of hits that Aquaveil absorbs before being removed
            833 =>'SONG_RECAST_DELAY', # Reduces song recast time in seconds.
            890 =>'ENH_MAGIC_DURATION', # Enhancing Magic Duration increase %
            891 =>'ENHANCES_COURSERS_ROLL', # Courser's Roll Bonus % chance
            892 =>'ENHANCES_CASTERS_ROLL', # Caster's Roll Bonus % chance
            893 =>'ENHANCES_BLITZERS_ROLL', # Blitzer's Roll Bonus % chance
            894 =>'ENHANCES_ALLIES_ROLL', # Allies' Roll Bonus % chance
            895 =>'ENHANCES_TACTICIANS_ROLL', # Tactician's Roll Bonus % chance
            902 =>'OCCULT_ACUMEN', # Grants bonus TP when dealing damage with elemental or dark magic

            909 =>'QUICK_MAGIC', # Percent chance spells cast instantly (also reduces recast to 0, similar to Chainspell)

        # Automaton mods
            842 =>'AUTO_DECISION_DELAY', # Reduces the Automaton's global decision delay
            843 =>'AUTO_SHIELD_BASH_DELAY', # Reduces the Automaton's global shield bash delay
            844 =>'AUTO_MAGIC_DELAY', # Reduces the Automaton's global magic delay
            845 =>'AUTO_HEALING_DELAY', # Reduces the Automaton's global healing delay
            846 =>'AUTO_HEALING_THRESHOLD', # Increases the healing trigger threshold
            848 =>'AUTO_SHIELD_BASH_SLOW', # Adds a slow effect to Shield Bash
            849 =>'AUTO_TP_EFFICIENCY', # Causes the Automaton to wait to form a skillchain when its master is > 90% TP
            850 =>'AUTO_SCAN_RESISTS', # Causes the Automaton to scan a target's resistances
            938 =>'AUTO_STEAM_JACKET', # Causes the Automaton to mitigate damage from successive attacks of the same type
            939 =>'AUTO_STEAM_JACKED_REDUCTION', # Amount of damage reduced with Steam Jacket
            940 =>'AUTO_SCHURZEN', # Prevents fatal damage leaving the automaton at 1HP and consumes an Earth manuever
            941 =>'AUTO_EQUALIZER', # Reduces damage received according to damage taken
            942 =>'AUTO_PERFORMANCE_BOOST', # Increases the performance of other attachments by a percentage
            943 =>'AUTO_ANALYZER', # Causes the Automaton to mitigate damage from a special attack a number of times

        # Mythic Weapon Mods
            521 =>'AUGMENTS_ABSORB', # Direct Absorb spell increase while Liberator is equipped (percentage based)
            524 =>'AOE_NA', # Set to 1 to make -na spells/erase always AoE w/ Divine Veil
            525 =>'AUGMENTS_CONVERT', # Convert HP to MP Ratio Multiplier. 'Value' =>MP multiplier rate.
            526 =>'AUGMENTS_SA', # Adds Critical Attack Bonus to Sneak Attack, percentage based.
            527 =>'AUGMENTS_TA', # Adds Critical Attack Bonus to Trick Attack, percentage based.
            873 =>'AUGMENTS_FEINT', # Feint will give another -10 Evasion per merit level
            886 =>'AUGMENTS_ASSASSINS_CHARGE', # Gives Assassin's Charge +1% Critical Hit Rate per merit level
            887 =>'AUGMENTS_AMBUSH', # Gives +1% Triple Attack per merit level when Ambush conditions are met
            889 =>'AUGMENTS_AURA_STEAL', # 20% chance of 2 effects to be dispelled or stolen per merit level
            912 =>'AUGMENTS_CONSPIRATOR', # Applies Conspirator benefits to player at the top of the hate list
            564 =>'JUG_LEVEL_RANGE', # Decreases the level range of spawned jug pets. Maxes out at 2.
            828 =>'FORCE_JUMP_CRIT', # Critical hit rate bonus for jump and high jump
            834 =>'QUICK_DRAW_DMG_PERCENT', # Percentage increase to QD damage

        # Crafting food effects
            851 =>'SYNTH_SUCCESS', # Rate of synthesis success
            852 =>'SYNTH_SKILL_GAIN', # Synthesis skill gain rate
            861 =>'SYNTH_FAIL_RATE', # Synthesis failure rate (percent)
            862 =>'SYNTH_HQ_RATE', # High-quality success rate (not a percent)
            916 =>'DESYNTH_SUCCESS', # Rate of desynthesis success
            917 =>'SYNTH_FAIL_RATE_FIRE', # Amount synthesis failure rate is reduced when using a fire crystal
            918 =>'SYNTH_FAIL_RATE_ICE', # Amount synthesis failure rate is reduced when using a ice crystal
            919 =>'SYNTH_FAIL_RATE_WIND', # Amount synthesis failure rate is reduced when using a wind crystal
            920 =>'SYNTH_FAIL_RATE_EARTH', # Amount synthesis failure rate is reduced when using a earth crystal
            921 =>'SYNTH_FAIL_RATE_LIGHTNING', # Amount synthesis failure rate is reduced when using a lightning crystal
            922 =>'SYNTH_FAIL_RATE_WATER', # Amount synthesis failure rate is reduced when using a water crystal
            923 =>'SYNTH_FAIL_RATE_LIGHT', # Amount synthesis failure rate is reduced when using a light crystal
            924 =>'SYNTH_FAIL_RATE_DARK', # Amount synthesis failure rate is reduced when using a dark crystal
            925 =>'SYNTH_FAIL_RATE_WOOD', # Amount synthesis failure rate is reduced when doing woodworking
            926 =>'SYNTH_FAIL_RATE_SMITH', # Amount synthesis failure rate is reduced when doing smithing
            927 =>'SYNTH_FAIL_RATE_GOLDSMITH', # Amount synthesis failure rate is reduced when doing goldsmithing
            928 =>'SYNTH_FAIL_RATE_CLOTH', # Amount synthesis failure rate is reduced when doing clothcraft
            929 =>'SYNTH_FAIL_RATE_LEATHER', # Amount synthesis failure rate is reduced when doing leathercraft
            930 =>'SYNTH_FAIL_RATE_BONE', # Amount synthesis failure rate is reduced when doing bonecraft
            931 =>'SYNTH_FAIL_RATE_ALCHEMY', # Amount synthesis failure rate is reduced when doing alchemy
            932 =>'SYNTH_FAIL_RATE_COOK', # Amount synthesis failure rate is reduced when doing cooking

            570 =>'WEAPONSKILL_DAMAGE_BASE', # Specific to 1 Weaponskill: See modifier.h for how this is used
            840 =>'ALL_WSDMG_ALL_HITS', # Generic (all Weaponskills) damage, on all hits.
        # Per https://www.bg-wiki.com/bg/Weapon_Skill_Damage we need all 3..
            841 =>'ALL_WSDMG_FIRST_HIT', # Generic (all Weaponskills) damage, first hit only.
            949 =>'WS_NO_DEPLETE', # % chance a Weaponskill depletes no TP.
            980 =>'WS_STR_BONUS', # % bonus to str_wsc.
            957 =>'WS_DEX_BONUS', # % bonus to dex_wsc.
            981 =>'WS_VIT_BONUS', # % bonus to vit_wsc.
            982 =>'WS_AGI_BONUS', # % bonus to agi_wsc.
            983 =>'WS_INT_BONUS', # % bonus to int_wsc.
            984 =>'WS_MND_BONUS', # % bonus to mnd_wsc.
            985 =>'WS_CHR_BONUS', # % bonus to chr_wsc.

        # Circle Abilities Extended Duration from AF/AF+1
            857 =>'HOLY_CIRCLE_DURATION',
            858 =>'ARCANE_CIRCLE_DURATION',
            859 =>'ANCIENT_CIRCLE_DURATION',

        # Other
            860 =>'CURE2MP_PERCENT', # Converts % of "Cure" amount to MP
            910 =>'DIVINE_BENISON', # Adds fast cast and enmity reduction to -Na spells (includes Erase). Enmity reduction is half of the fast cast amount
            880 =>'SAVETP', # SAVETP Effect for Miser's Roll / ATMA / Hagakure.
            898 =>'SMITE', # Att increase with H2H or 2H weapons
            899 =>'TACTICAL_GUARD', # Tp gain increase when guarding
            976 =>'GUARD_PERCENT', # Guard Percent
            903 =>'FENCER_TP_BONUS', # TP Bonus to weapon skills from Fencer Trait
            904 =>'FENCER_CRITHITRATE', # Increased Crit chance from Fencer Trait
            905 =>'SHIELD_DEF_BONUS', # Shield Defense Bonus
            946 =>'SNEAK_DURATION', # Additional duration in seconds
            947 =>'INVISIBLE_DURATION', # Additional duration in seconds
            948 =>'BERSERK_EFFECT', # Conqueror Berserk Effect
            954 =>'BERSERK_DURATION', # Berserk Duration
            955 =>'AGGRESSOR_DURATION', # Aggressor Duration
            956 =>'DEFENDER_DURATION', # Defender Duration
            959 =>'CARDINAL_CHANT',
            960 =>'INDI_DURATION',
            961 =>'GEOMANCY',
            962 =>'WIDENED_COMPASS',
            968 =>'MENDING_HALATION',
            969 =>'RADIAL_ARCANA',
            970 =>'CURATIVE_RECANTATION',
            971 =>'PRIMEVAL_ZEAL',
            965 =>'COVER_TO_MP', # Converts a successful cover's phsyical damage to MP
            966 =>'COVER_MAGIC_AND_RANGED', # Redirects ranged and single target magic attacks to the cover ability user
            967 =>'COVER_DURATION', # Increases Cover Duration
            974 =>'WYVERN_SUBJOB_TRAITS', # Adds subjob traits to wyvern
            975 =>'GARDENING_WILT_BONUS', # Increases the number of Vanadays a plant can survive before it wilts

            986 =>'WYVERN_BREATH_MACC',
        }
        @mods[modId]
    end
end
